name: Configuration Split
type: module
description: Configuration filter for importing and exporting split config
core: 8.x
core_version_requirement: ^8 || ^9
package: Config
configure: entity.config_split.collection
dependencies:
  - config_filter:config_filter

# Information added by Drupal.org packaging script on 2020-04-30
version: '8.x-1.5-rc1'
project: 'config_split'
datestamp: 1588277565
